#!/bin/bash
#SBATCH --job-name=EEG_stim_cnt         # create a short name for your job
#SBATCH --nodes=1                # node count
#SBATCH --ntasks=1               # total number of tasks across all nodes
#SBATCH --cpus-per-task=40
#SBATCH --time=1000:00:00          # total run time limit (HH:MM:SS)
#SBATCH --mem=200G
#SBATCH --partition=highmem1
#SBATCH --qos=highmem1
#SBATCH --account=iacc_gbuzzell
#SBATCH --output=%x-%j.out
#SBATCH --mail-type=end          # send email when job ends
#SBATCH --mail-user=fzaki001@fiu.edu

module load matlab-2021b

pwd; hostname; date
echo "flurm cpus per task: $SLURM_CPUS_PER_TASK"

matlab -nodisplay -nosplash -r "stim_cnt_check_processed_csd"
#matlab -nodisplay -nosplash -r "check_ch_nums"
errors=$(cat ${SLURM_JOB_NAME}-${SLURM_JOB_ID}.out | grep "Error")
if [[ -z ${errors} ]]; then
    echo "EEG preprocessing on subjects $subjects_to_process complete."
else
    echo "EEG preprocessing on subjects $subjects_to_process exited with errors: ${errors}"
fi

#singularity exec $sing_image python3 update-tracker-postMADE.py $dataset $session

#echo "updated tracker"
