#!/bin/bash
#SBATCH --job-name=csd        # create a short name for your job
#SBATCH --nodes=1                # node count
#SBATCH --ntasks=1               # total number of tasks across all nodes
#SBATCH --cpus-per-task=40
#SBATCH --time=1000:00:00          # total run time limit (HH:MM:SS)
#SBATCH --mem=200G
#SBATCH --partition=highmem1
#SBATCH --qos=highmem1
#SBATCH --account=iacc_gbuzzell
#SBATCH --output=%x-%j.out
#SBATCH --mail-type=end          # send email when job ends
#SBATCH --mail-user=fzaki001@fiu.edu

module load matlab-2021b

pwd; hostname; date
echo "flurm cpus per task: $SLURM_CPUS_PER_TASK"
SESSION_ARG=$1
matlab -nodisplay -nosplash -r "session = '$SESSION_ARG'; transform_csd; exit;"
