## To run, this script requires some additional R packages to be installed, the rcpp file, as well as a data file.
#rm(list = ls())
sink(sprintf("output_log_%s.txt", format(Sys.time(),'%y-%m-%d_%H-%M-%S')), split = TRUE)
setwd("../")

library("DEoptim")
library("Rcpp")
#------------------------------------------------------------------------------
# Fit function for the SSP model
fitFunctionSSP <- function(
    parms, # generated by DEoptim within specified boundaries when DEoptim is called
    nTrials, # how many trials to simulate per condition 
    cutPoints, # used for rt binning (must be len = 4)
    humanProps, # proportion of trials for a given accuracy condition relative to all trials in a given congruency condition (must be len = 4)
    HumanTrialCounts # number of real data trials for each congruency condition (must be len = 2)
){
  
  # source the rcpp function that will be used for simulating the model (implemented in cpp to improve speed)
  # The rcpp file contains the actual "model"; all of the code in this script is for loading data, calling 
  # the model to simulate, fit the data, etc.
  Rcpp::sourceCpp("simSSP_model_GB_noScale.cpp")
  
  # initialize empty matrix for simulation data with three columns (RT, accuracy, congruency)
  # and with rows = nTrials
  SimData <- matrix(0, nrow = nTrials * 2, ncol = 3)
  colnames(SimData) <- c("rt", "accuracy", "congruent")
  SimData <- data.frame(SimData)
  
  # simulate the ssp model, using current parms and return simulated data (trial level RT and accuracy)
  # to simulate data, call an rcpp function (rcpp used to speed up simulation, and in turn, model fitting)
  # Call simulation function twice, once for congruent, once for incongruent
  # 
  # simulate congruent trials and save simulated trial-level data
  set.seed(42) # Before running simulation for this param set, set random number seed, so pseudo-randomness is identical across param sets
  # make sure that the "simSSP_model_GBnoScale" bit is called whatever it calls itself inside the actual .cpp file
  # in SimData, the 1st column is RT and the 2nd is accuracy as per cpp function output
  SimData[1:nTrials, 1:2] <- simSSP_model_GBnoScale(
    parms, # a ter p rd sda
    trialType = 1, # congruent because 1 stays for congruent in the cpp function
    nTrials,
    dt = 0.001,
    vari = 0.01
    ) 
  SimData[1:nTrials, 3] <- 1 # congruent because in my input dataset 1 stays for congruent
  set.seed(as.numeric(Sys.time())) # now that simulation has been run, reset the random seed to system time (to not mess up other functions using random numbers)
  
  # Now simulate incongruent trials and save simulated trial-level data
  set.seed(42) # Before running simulation for this param set, set random number seed, so psuedo-ranndomeass is identical across param sets
  # make sure that the "simSSP_model_GBnoScale" bit is called whatever it calls itself inside the actual .cpp file
  SimData[(nTrials + 1):(nTrials * 2), 1:2] <- simSSP_model_GBnoScale(
    parms,
    trialType = 2, # incongruent because 2 stays for incongruent in the cpp function
    nTrials, # number of trials to simulate
    dt = 0.001,
    vari = 0.01
  )
  SimData[(nTrials + 1):(nTrials * 2), 3] <- 0 # incongruent because in my input dataset 0 stays for incongruent
  set.seed(as.numeric(Sys.time())) # now that simulation has been run, reset the random seed to system time (to not mess up other functions using random numbers)
  
  # Identify the proportions in each (human-based) cutoff, for the simulated data
  #
  # initialize variable to hold bin proportions for sim data
  # (1=congruent-correct;2=congruent-error;3=incongruent-correct;4=incongruent-error)
  simProps <- list()
  # initialize variable to hold bin proportion differences for human and sim data
  # (1=congruent-correct;2=congruent-error;3=incongruent-correct;4=incongruent-error)
  binDiffs <- list()
  # initialize variable (vector) to hold sums of bin proportion differences for human and sim data
  # (1=congruent-correct;2=congruent-error;3=incongruent-correct;4=incongruent-error)
  sum_binDiffs <- numeric(4)
  # initialize counter variable
  counter <- numeric(1)
  #
  # Loop over conditions % number of conditions = 2 (congruent, incongruent)
  for (i in 1:2) {
    # clear out variable for this iteration of loop
    sim_condData <- NULL
    # select congruent/incongruent condition
    if (i == 1) {
      sim_condData <- subset(SimData, SimData$congruent == 1) # congruent
    } else if (i == 2) {
      sim_condData <- subset(SimData, SimData$congruent == 0) # incongruent
    }
    
    # loop over accuracy (correct, error)
    for (j in 1:2) {
      if (j == 1) {
        trialAccuracy = 1 # correct
        counter <- counter+1
      } else if (j == 2) {
        trialAccuracy = 0 # error
        counter <- counter+1
      }
      sim_accCondData <- subset(sim_condData, sim_condData$accuracy == trialAccuracy) # select the data 
      
      # determine number of bins (not quantiles) based on which condition and if this is error or correct
      nBins <- length(cutPoints[[counter]])+1 # add 1 to number of cutPoints (or quantiles) to get bins
      
      # initialize temporary vector to hold proportions; this will be written into the simProps list after the bin loop
      temp_simProps<-NULL
      temp_simProps<-numeric(nBins)
      
      # initialize temporary vector to bin proportion difference between human and sim data;
      # this will be written into the binDiffs list after the bin loop
      temp_binDiffs<-NULL
      temp_binDiffs<-numeric(nBins)
      
      # loop over each bin, find the bin boundaries, and calculate the proportion of RT in each bin
      # PROPORTIONS ARE NUMBER TRIALS IN THIS BIN, FOR THIS CONDITION, DIVIDED BY TOTAL TRIALS IN THIS CONDITION (CORRECT + ERROR)
      # [ (# trials in this bin) / (# trials in all correct bins for this condition + # trials in all error bins for this condition) ]
      # for simulated data, number of trials inn each condition = nTrials
      for (k in 1:nBins) {
        
        # initialize variable to hold data for this bin
        binData <-NULL
        
        # first bin
        if (k == 1) {
          # get the data in the current bin
          binData <- subset(sim_accCondData, sim_accCondData$rt <= cutPoints[[counter]][k])
          # find the proportion of data in this bin (proportion out of both error and correct, for this condition)
          # if the proportion is zero, convert to a very small number (neccesary for later chi-square computation)
          if (length(binData[, 1]) > 0) {
            temp_simProps[k] <- length(binData[, 1]) / nTrials #save actual prop if non-zero
          } else {
            temp_simProps[k] <- .0000001 #default to very small value if prop is zero
          }
          
          # (for chi square): compute difference between human and sim props, square, divide
          # by sim props, multiply by number of trials for this condition (in human data)
          temp_binDiffs[k] <-  HumanTrialCounts[i]*((humanProps[[counter]][k] - temp_simProps[k])^2/temp_simProps[k])
        }
        # middle bins
        if (k > 1 & k < nBins) {
          # get the data in the current bin
          binData <- subset(sim_accCondData, sim_accCondData$rt > cutPoints[[counter]][k-1] & sim_accCondData$rt <= cutPoints[[counter]][k])
          # find the proportion of data in this bin (proportion out of both error and correct, for this condition)
          # if the proportion is zero, convert to a very small number (neccesary for later chi-square computation)
          if (length(binData[, 1]) > 0) {
            temp_simProps[k] <- length(binData[, 1]) / nTrials #save actual prop if non-zero
          } else {
            temp_simProps[k] <- .0000001 # default to very small value if prop is zero
          }
          # (for chi square): compute difference between human and sim props, square, divide
          # by sim props, multiply by number of trials for this condition (in human data)
          temp_binDiffs[k] <-  HumanTrialCounts[i]*((humanProps[[counter]][k] - temp_simProps[k])^2/temp_simProps[k])         
        }
        # last bin
        if (k == nBins) {
          # get the data in the current bin
          binData <- subset(sim_accCondData, sim_accCondData$rt > cutPoints[[counter]][k-1])
          # find the proportion of data in this bin (proportion out of both error and correct, for this condition)
          # if the proportion is zero, convert to a very small number (necessary for later chi-square computation)
          if (length(binData[, 1]) > 0) {
            temp_simProps[k] <- length(binData[, 1]) / nTrials #save actual prop if non-zero
          } else {
            temp_simProps[k] <- .0000001 #default to very small value if prop is zero
          }
          # (for chi square): compute difference between human and sim props, square, divide
          # by sim props, multiply by number of trials for this condition (in human data)
          temp_binDiffs[k] <-  HumanTrialCounts[i]*((humanProps[[counter]][k] - temp_simProps[k])^2/temp_simProps[k])
        }
      } # END Loop over bins (k), for this correct/error (j), for this congruency condition (i)
      
      # save the human props (from temp_simProps vector) into simProps list
      simProps[[counter]]<-temp_simProps
      
      # save the bin proportion differences between human and sim data (from temp_binDiffs vector) into binDiffs list
      binDiffs[[counter]]<-temp_binDiffs
      # sum over the bin proportion differences (for chi square)
      sum_binDiffs[[counter]] <- sum(temp_binDiffs)
      
    } # END Loop over correct/error (j), for this condition (i)
    
  }# END Loop over congruent/incongruent (i)
  
  # compute the chi-squre statistic by summing across all the bin proportion differences (diff between human and sim)
  chiSquare <- sum(sum_binDiffs)
  
  # return the chiSuare from the fitFunctionSSP, unless chiSquare is infinite, then return really large value instead
  if (chiSquare == Inf) {
    return (.Machine$double.xmax)
  } else {
    return (chiSquare)
  }
  
}# End of fitFunctionSSP
#------------------------------------------------------------------------------
# At the beginning of your R script
args <- commandArgs(trailingOnly = TRUE)
start_idx <- as.numeric(args[1])
end_idx <- as.numeric(args[2])

recover_params <- function(start_idx, end_idx) {
	# analysis_path = "/Users/fzaki001/thrive-theta-ddm/" # local
	# analysis_path = "/Users/fzaki001/thrive-theta-ddm/" # local
	analysis_path = "/home/data/NDClab/analyses/thrive-theta-ddm/" # HPC
	output_sim_path <- sprintf("%s/derivatives/behavior/ddm_recovery/sim_data/", analysis_path)
	output_fit_path <- sprintf("%s/derivatives/behavior/ddm_recovery/fit_data/", analysis_path)

	# how many trials to simulate per condition
	#nTrials_to_sim = c(50, 100, 200, 500, 1000, 5000)
	#nTrials_to_sim = c(5, 10, 25)
        #nTrials_to_sim = c(12, 14, 16, 18, 20)
        nTrials_to_sim = c(6, 7, 8, 9)

	dt <- 0.001
	vari <- 0.01

	# set up default parms and upper/lower values (for now, not using default values, just upper/lower with DEoptim)
	Upper <- c(0.232, 0.420, 0.630, 0.067,  3.093); #mean of white 2011 Exp1 plus 5 sd
	Lower <- c(0.032, 0.180, 0.130, 0.0001, 0.493); #mean of white 2011 Exp1 minus 5 sd
	nTrials <- 10000
	output_fit_file <- sprintf(
	  "recovered_params_%s.csv",
	  format(Sys.time(),'%y_%m_%d_%H_%M_%S') # will indicate start time
	  )
	numParams <- length(Upper)
	fitOutput <-data.frame(matrix(ncol=9, nrow=0))
	colnames(fitOutput) <- c("subject", "a", "ter", "p", "rd", "sda", "fitStat", "iteNum", "seed")
	fitOutput <- data.frame(fitOutput)

	# also write a .csv to append parms to at the end of loops
	write.csv(fitOutput, sprintf("%s/%s", output_fit_path, output_fit_file), row.names=FALSE, na="", quote = F)

	for (condition in nTrials_to_sim) {
	  
	  for (cb in seq(1, 100)[start_idx:end_idx]) {
	    start_time <- Sys.time()
	    seed <- cb + sample(1:10e6, 1)
	    set.seed(seed)  # For reproducibility
	    sim_data <- read.csv(sprintf("%s/sim_data_%s_%s.csv", output_sim_path, condition, cb))
	    
	    HumanTrialCounts <- numeric(2) # just a vector of zeros
	    
	    # initialize variables to hold human quantiles, cutpoints, bin proportions
	    # (1=congruent-correct; 2=congruent-error; 3=incongruent-correct; 4=incongruent-error)
	    quantiles <- list()
	    cutPoints <- list()
	    humanProps <- list()
	    
	    # initialize counter variable, so that for each congruency-accuracy pair variables like quantiles, bins, will have corresponding index
	    counter <- numeric(1)
	    
	    # For this condition, and based on the HUMAN data, determine whether the number of trials (t)
	    # is <= 5, 5 < t <= 10, Ne > 10. Set the number of  bins to be: 2 (.5), 4 (.1, .5, .9),
	    # or 6 (.1, .3, .5, .7, .9) and identify the RT cutoffs that will divide the  trial data
	    # into the appropriate number of bins. If there are no trials for this condition, then data
	    # are not included in chi-square for this condition.
	    #
	    # loop over accuracy (correct, error)
	    # Loop over congruency conditions
	    for (i in 1:2) {
	      # clear out variable for this iteration of loop
	      condData <- NULL
	      
	      # select congruent/incongruent condition
	      if (i == 1) {
		condData <- subset(sim_data, sim_data$congruent == 1) # congruent
	      } else if (i == 2) {
		condData <- subset(sim_data, sim_data$congruent == 0) # incongruent
	      }
	      
	      # For this condition, and based on the HUMAN data, save the total number of trials
	      # in this condition (errors and corrects)
	      HumanTrialCounts[i] <- nrow(condData)
	      for (j in 1:2) {
		
		# select correct/error data for this condition
		if (j == 1) {
		  trialAccuracy = 1 # correct
		  counter <- counter+1
		} else if (j==2) {
		  trialAccuracy = 0 # error
		  counter <- counter+1
		}
		accCondData <- subset(condData, condData$accuracy == trialAccuracy) #select the data 
		
		# determine the proper number of quantiles/bins based on number of trials for this condition-accuracy
		if (nrow(accCondData)<=5) {
		  quantiles[[counter]] = c(.5)
		}
		if (nrow(accCondData)>5 & nrow(accCondData)<=10) {
		  quantiles[[counter]] = c(.1, .5, .9)
		}
		if (nrow(accCondData)>10) {
		  quantiles[[counter]] = c(.1, .3, .5, .7, .9)
		}
		
		# calculate RT cutoffs corresponding to quantiles 
		cutPoints[[counter]] <- as.numeric(quantile(accCondData$rt, quantiles[[counter]]))
		
		# determine number of bins (not quantiles) based on which condition and if this is error or correct
		nBins <- length(cutPoints[[counter]])+1 #add 1 to number of cutPoints (or quantiles) to get bins
		
		# initialize temporary vector to hold proportions; this will be written into the humanProps list after the bin loop
		temp_humanProps<-NULL
		temp_humanProps<-numeric(nBins)
		
		# loop over each bin, find the bin boundaries, and calculate the proportion of RT in each bin
		# PROPORTIONS ARE NUMBER TRIALS IN THIS BIN, FOR THIS CONDITION (ACC-CON), DIVIDED BY TOTAL TRIALS IN THIS CONDITION (CORRECT + ERROR)
		# [ (# trials in this bin) / (# trials in all correct bins for this condition + # trials in all error bins for this condition) ]
		for (k in 1:nBins) {
		  
		  #initialize variable to hold data for this bin
		  binData <-NULL
		  
		  # first bin
		  if (k == 1) {
		    # get the data in the current bin
		    binData <- subset(accCondData, accCondData$rt <= cutPoints[[counter]][k])
		    # find the proportion of data in this bin (proportion out of both error and correct, for this condition)
		    # if the proportion is zero, convert to a very small number (neccesary for later chi-square computation)
		    if (length(binData[, 1]) > 0) {
		      temp_humanProps[k] <- length(binData[, 1]) / HumanTrialCounts[i]
		    } else {
		      temp_humanProps[k] <- .0000001 #default to very small value if prop is zero
		    }
		  }
		  
		  # middle bins
		  if (k > 1 & k < nBins) {
		    # get the data in the current bin
		    binData <- subset(accCondData, accCondData$rt > cutPoints[[counter]][k-1] & accCondData$rt <= cutPoints[[counter]][k])
		    # find the proportion of data in this bin (proportion out of both error and correct, for this condition)
		    # if the proportion is zero, convert to a very small number (necessary for later chi-square computation)
		    if (length(binData[, 1]) > 0) {
		      temp_humanProps[k] <- length(binData[, 1]) / HumanTrialCounts[i]
		    } else {
		      temp_humanProps[k] <- .0000001 #default to very small value if prop is zero
		    }        
		  }
		  
		  # last bin
		  if (k == nBins) {
		    # get the data in the current bin
		    binData <- subset(accCondData, accCondData$rt > cutPoints[[counter]][k-1])
		    # find the proportion of data in this bin (proportion out of both error and correct, for this condition)
		    # if the proportion is zero, convert to a very small number (neccesary for later chi-square computation)
		    if (length(binData[, 1]) > 0) {
		      temp_humanProps[k] <- length(binData[, 1]) / HumanTrialCounts[i]
		    } else {
		      temp_humanProps[k] <- .0000001 #default to very small value if prop is zero
		    }        
		  }
		} # END Loop over bins (k), for this correct/error (j), for this condition (i)
		
		# save the human props (from temp_humanProps vector) into humanProps list
		humanProps[[counter]]<-temp_humanProps
		
	      } # END Loop over correct/error (j), for this condition (i)
	      
	    } # end congruent/incongruent (i) loop
            # modelStart <- "Wow, nice model you got there! I better start fitting it... Model Fit Running; Please Wait..."
	    assign("nTrials", nTrials, envir = .GlobalEnv)
            assign("cutPoints", cutPoints, envir = .GlobalEnv)
            assign("humanProps", humanProps, envir = .GlobalEnv)
            assign("HumanTrialCounts", HumanTrialCounts, envir = .GlobalEnv)
            print(
	      sprintf(
		"Start fitting model for %s-%s ...",
		condition, cb
	      )
	    )
	    # perform the fit
	    OptimFitResults <- DEoptim(
	      fitFunctionSSP,
	      lower = Lower,
	      upper = Upper,
	      control = DEoptim.control(
		itermax = 200,
		steptol = 20,
		parallelType = "auto",
		packages = c("Rcpp"),
		parVar = c("nTrials","cutPoints","humanProps","HumanTrialCounts")
	      ),
	      nTrials = nTrials,
	      cutPoints = cutPoints,
	      humanProps = humanProps,
	      HumanTrialCounts = HumanTrialCounts,
	      fnMap=NULL
	    )
	    modelFinished <- "Woohoo! Model Fit Finished!!"
	    print(
	      sprintf(
		"%s %s-%s",
		modelFinished, condition, cb
	      )
	    )
	    # print(c(modelFinished, s, subList[s], " pre_accuracy: ", preAccuracy, " condition_soc: ", conditionSoc))
	    subject <- sprintf("%s_%s", condition, cb)
	    
	    # pull best fitting parms- 1/5- a
	    bestParms1 <- as.numeric(OptimFitResults$optim$bestmem[1])
	    # pull best fitting parms- 2/5- ter
	    bestParms2 <- as.numeric(OptimFitResults$optim$bestmem[2])
	    # pull best fitting parms- 3/5- p
	    bestParms3 <- as.numeric(OptimFitResults$optim$bestmem[3])
	    # pull best fitting parms- 4/5- rd
	    bestParms4 <- as.numeric(OptimFitResults$optim$bestmem[4])
	    # pull best fitting parms- 5/5- sda
	    bestParms5 <- as.numeric(OptimFitResults$optim$bestmem[5])
	    
	    # pull out the best fitting fitStat
	    bestFitStat <- as.numeric(OptimFitResults$optim$bestval)
	    
	    # pull out stop iteration
	    iter <- as.numeric(OptimFitResults$optim$iter)
	    
	    newRow<- NULL 
	    # make new row with values created above
	    newRow <- data.frame(subject, bestParms1, bestParms2, bestParms3, bestParms4, bestParms5, bestFitStat, iter, seed)
	    
	    # appending the parms to the csv created before the loops
	    write.table(newRow, file=sprintf("%s/%s", output_fit_path, output_fit_file), sep=",", append=TRUE, col.names = FALSE, row.names = FALSE)
	    end_time <- Sys.time()
	    alloc_time <- end_time - start_time
	    
	    print(
	      sprintf("All finished in %s minutes",
		      alloc_time / 60)
	    )
	  } # end cb (cb) lop
	} # end ntrials (condition) loop
}

# Call the function with command line arguments
if (length(args) == 2) {
    recover_params(start_idx, end_idx)
} else {
    stop("Please provide start and end indices as arguments")
}
sink()
